<?php

namespace Tests\Feature;

use App\Models\Label;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class LabelTest extends TestCase
{
    /**
     * A basic feature test example.
     *
     * @return void
     */
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = $this->authUser();
    }

    public function test_user_can_create_new_label()
    {
        $label = Label::factory()->raw();

        $this->postJson(route('label.store', $label))
        ->assertCreated();

        $this->assertDatabaseHas('labels', ['title' => $label['title'], 'color' => $label['color']]);
    }

    public function test_delete_label()
    {
        $label = $this->createLabel();

        $this->deleteJson(route('label.destroy', $label->id))->assertNoContent();

        $this->assertDatabaseMissing('labels', ['title' => $label->title]);
    }

    public function test_update_label()
    {
        $label = $this->createLabel();

        $this->patchJson(route('label.destroy', $label->id), ['title' => $label->title, 'color' => 'new color'])->assertOk();

        $this->assertDatabaseHas('labels', ['title' => $label->title, 'color' => 'new color']);
    }

    public function test_fetch_all_label()
    {
        $label = $this->createLabel(['user_id' => $this->user->id]);
        $this->createLabel();

        $response = $this->getJson(route('label.index'))->assertOk()->json();

        $this->assertEquals($response[0]['title'], $label->title);
    }
}
